### ISSUE TITLE
test.sh produces weird output

### ISSUE THREAD

**Issue by SeventyB** [rstemmer/libprinthex#4] opened 2023-10-22 17:09 UTC
The output from the test.sh: 

<img width="1403" alt="Screenshot 2023-10-22 at 19 33 01" src="https://github.com/rstemmer/libprinthex/assets/28990724/f5dd0db6-c2aa-44fc-a3c3-35f1fb7adc31">

The output is reproducible by building the docker image 
```bash
docker build . -t showdump
```
using the following Dockerfile: 
```Dockerfile
FROM ubuntu:latest
RUN apt-get update && apt-get install -y clang git libz-dev
RUN git clone https://github.com/rstemmer/libprinthex.git
RUN cd libprinthex && ./build.sh && ./install.sh
WORKDIR /libprinthex
CMD [ "bash", "./test.sh" ]
```
and running it:
```bash
docker run showdump
```

**Comment by rstemmer** [comment] 2023-10-22 20:32
Hi

I can reproduce the warning when building the test - will be fixes soon.
But that's not the reason of the wired output.

It looks like some ANSI escape sequences are not correctly processed. 
Can you tell me what value the environment variable `TERM` is? → `echo $TERM`.

The interesting question is, what `TERM` variable matters? Inside or outside the container :thinking: 
I'm not yet very experienced with containerization.

Can you also tell me what host system you use? I then try to setup a VM with docker to try to reproduce the issue.

**Comment by SeventyB** [comment] 2023-10-23 06:42
It was reproduced on macOS Catalina version 10.15.7 with the docker desktop v4.9.0.
```bash
λ ~/ docker run -it ubuntu
root@a4bd9b47d267:/# echo $TERM
xterm
root@a4bd9b47d267:/# 
exit
λ ~/ echo $TERM
xterm-256color
λ ~/ 
λ ~/ 
```

**Comment by rstemmer** [comment] 2023-10-24 08:46
Regarding [stackoverflow](https://stackoverflow.com/questions/28986776/ansi-escape-sequence-save-restore-cursor-position-support) it is save to switch to ESC 7/8 instead using CSI s/u.

The fixed version is now on the develop branch including your changed to the build scripts to use the library on MacOS.
For now I only tested the changes on MacOS.
After some tests on Linux I merge everything to master and create a new release.

**Comment by rstemmer** [comment] 2023-10-24 13:23
Issue should be fixed.

**Closed by rstemmer** 2023-10-24 13:23 UTC
Labels: bug
